import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_component/home/header";
import Footer from "./_component/home/footer";
import SessionProviderWrapper from "./ClientProvider";
import { AuthProvider } from "./context/AuthContext";
import { ProductsProvider } from "./context/ProductsContext";
import { CategoriesProvider } from "./context/categoriesContext";
import { CartProvider } from "./context/CartContext";
import { OrdersProvider } from "./context/OrderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GigaByte Damietta",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <AuthProvider>
            <CategoriesProvider>
              <ProductsProvider>
                <CartProvider>
                  <OrdersProvider>
                    <Header />
                    {children}
                    <Footer />
                  </OrdersProvider>
                </CartProvider>
              </ProductsProvider>
            </CategoriesProvider>
          </AuthProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
