import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_component/home/header";
import Footer from "./_component/home/footer";
import SessionProviderWrapper from "./ClientProvider"; // Remove curly braces
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
          </AuthProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
